name: flutter_happy_place
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  flutter_riverpod: ^3.0.3
  image_picker: ^1.2.0
  location: ^8.0.1
  flutter_map: ^8.2.2
  flutter_dotenv: ^6.0.0
  geolocator: ^14.0.2
  http: ^1.5.0
  latlong2: ^0.9.1
  flutter_map_location_marker: ^10.1.0
  flutter_polyline_points: ^3.1.0
  path_provider: ^2.1.5
  path: ^1.9.1
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
